### ISSUE TITLE
Not working on AppleTV

### ISSUE THREAD

**Issue by Johan-Claesson** [lindell/home-assistant-tv4-play#17]
Hey! First of, great work with keeping this alive and making sure we all can enjoy programs from TV4 Play! Really appropriate you taking time to develop this :) 

Probably im doing something wrong, but just want to make an automation starting "Nyhetsmorgon" on our Apple TV in the morning. For now this how far it gets me, the program ID is for "Bäst i Test", as the other ones i try gives me an "unknow error". The screen in the bedroom flashes briefly and then it gets back to TV4 Play home screen. 

Could you maybe share a working example for your config, even tough it maybe isn't an Apple TV? 

Here is my test automation: 

```
alias: TV4 test
description: ""
triggers: []
conditions: []
actions:
  - action: media_player.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
        - media_player.bedroom
  - action: media_player.select_source
    metadata: {}
    data:
      source: TV4 Play
    target:
      entity_id:
        - media_player.bedroom
  - action: tv4_play.play_suggested
    metadata: {}
    data:
      program_id: 656771bf6316036b7178
      config_entry: 01JHFNEFT9F0YY8QWBR26VJR10
    target:
      entity_id: media_player.bedroom
mode: single
```

**Comment by lindell** [comment]
The only thing that should be needed is the last part action. Starting TV4 Play as source should do nothing as this integration plays a raw stream, not through "apps".

This started a bäst i test episode:
```yaml
action: tv4_play.play_suggested
target:
  entity_id:
    - media_player.kitchen_display
data:
  config_entry: 01JH3MMK34YWBDWHYNRD4KHP8Y
  program_id: 656771bf6316036b7178
```

There could be that missmatch in supported formats. 
Are you able to run this?
```yaml
action: media_player.play_media
data:
  media_content_type: video
  media_content_id: >-
    https://vod.streaming.a2d.tv/33d5b354-a206-4ab8-b6dd-cd3e41091350/aef997f0-798c-11ef-88a2-453f94b3407a_20797530.ism/.m3u8?start_index=3
target:
  entity_id: media_player.bedroom
```
